### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by xogeny** [moshee/airlift#2]
If I do a `go get -u ktkr.us/pkg/airlift`, I get the error:

```
	imports ktkr.us/pkg/gas: /Users/mtiller/Source/GoWorkspace/src/ktkr.us/pkg/gas exists but /Users/mtiller/Source/GoWorkspace/src/ktkr.us/pkg/gas/.git does not - stale checkout?
# cd .; git clone https://github.com/moshee/gas/out /Users/mtiller/Source/GoWorkspace/src/ktkr.us/pkg/gas/out
Cloning into '/Users/mtiller/Source/GoWorkspace/src/ktkr.us/pkg/gas/out'...
fatal: repository 'https://github.com/moshee/gas/out/' not found
```

**Comment by moshee** [comment]
Should be fixed. I've never actually tried this on a clean build environment before, some cruft facilitating my build.

**Comment by xogeny** [comment]
Still didn't work for me.  I get the same error as before.  I tried simplifying things by just running:

```
$ go get -u ktkr.us/pkg/gas/out
```

That does not work.

P.S. - You might want to consider using "drone.io" for CI.  I use it for several of my own Go projects.  The big benefit, for me, is exactly this issue of constantly shifting dependencies.  You have a cached copy of some dependency on your machine and you never realize that the API has changed since your last `go get`.  With "drone.io", it checks your code with each commit back go GitHub and sends you an email to let you know that clean builds still work.  Just a thought.

**Comment by moshee** [comment]
I tried a clean Docker image and it installed and ran fine. I fixed an issue with my custom import path; try deleting the downloaded stuff from before and `go get`ing again. At least it shouldn't give the stale checkout error any more.

I'll consider CI some time if people actually start using this. As far as I know you're the first one to actually attempt to install this from source. I have one tester who uses the binary releases.

**Comment by xogeny** [comment]
You are correct.  I setup a clean `GOPATH` and do the install and everything was fine.
