### ISSUE TITLE
Cannot get the projet

### ISSUE THREAD

**Issue by lightcode** [moshee/airlift#23]
Hi,

Few months ago, I've build your project to put it in the Docker Hub. But, recently I can't build the image. Go cannot get the package. Here is the error:

```console
$ docker build -t airlifd .
Sending build context to Docker daemon 671.7 kB
Step 1 : FROM golang
 ---> 12057194b5fc
Step 2 : MAINTAINER moshee <moshee@displaynone.us>
 ---> Running in a6114cb79e4d
 ---> a17f4955ca5f
Removing intermediate container a6114cb79e4d
Step 3 : RUN go get -u ktkr.us/pkg/airlift/cmd/airliftd
 ---> Running in 43504e065998
package ktkr.us/pkg/airlift/cmd/airliftd: unrecognized import path "ktkr.us/pkg/airlift/cmd/airliftd"
The command '/bin/sh -c go get -u ktkr.us/pkg/airlift/cmd/airliftd' returned a non-zero code: 1
```
I cannot get the project on my laptop neither. Maybe I miss something in the Go configuration but it seems like this is a 404 error from your repo.

**Comment by moshee** [comment]
Oh yeah, sorry, I've been switching physical servers and I'm still tweaking the service that handles go-get redirects (it does other stuff too). Only solution now is to manually git clone and rename the directory until I get around to that.

**Comment by lightcode** [comment]
OK. Have you consider to put import to GitHub in your code ? You have already all the dependencies on GitHub.

**Comment by moshee** [comment]
I used to. I set up a vanity go get import path because I am vain. Also I never really expected anyone to actually use my stuff.

Anyways, it should work now.

**Comment by lightcode** [comment]
Yes it works. Thank you.

I use your project because it's the only project that allows me to upload file on my server quickly and without use a big program with a database...
