### ISSUE TITLE
cmd/airliftd: optional syntax highlighting

### ISSUE THREAD

**Issue by ZackBoe** [moshee/airlift#33]
Hi! Been happily using airlift for a few years now.

I've thrown together a [working concept here](https://github.com/ZackBoe/airlift/commit/af9cc17fa72d6341d9f58ad28b3c95cf95cbaeee) using [chroma](https://github.com/alecthomas/chroma). I'd send a PR, but this is my first experience with golang, so I'm sure I've done a few wacky things.

[See here](https://github.com/ZackBoe/airlift/commit/af9cc17fa72d6341d9f58ad28b3c95cf95cbaeee#commitcomment-29202145) for thoughts/screenshots on my implementation.

**Comment by moshee** [comment]
I added my thoughts to the commit. I think the code looks fine overall with a few stylistic issues. If you want you can make the changes and try submitting the PR, or I can cherry pick the parts I want and commit it myself.

Thanks!

**Comment by ZackBoe** [comment]
I've made [some changes](https://github.com/ZackBoe/airlift/commits/syntax), including cleaning up a lot of the [logic for rendering raw files](https://github.com/ZackBoe/airlift/blob/syntax/cmd/airliftd/server.go#L413)!

Still unsure about a few things:
- handling airlift/config
I'd assume I should change this reference to back to `ktkr.us` before sending a PR. Will upgrading an existing install add the new preferences?
- likewise with [this](https://github.com/ZackBoe/airlift/commit/af9cc17fa72d6341d9f58ad28b3c95cf95cbaeee#diff-18a00cd2f1faec7f3e0dea6003b372b6L3), which I don't think I manually changed?
- having some issues with error templates rendering. I want to chalk this up to my golang install, but not positive.

Lemme know your thoughts on the changes so far and the above issues I'll send a PR! (or you can grab what you want ¯\\\_(ツ)\_/¯ )


![ca715bbf](https://user-images.githubusercontent.com/904055/40884393-e1a71972-66e0-11e8-9c9d-aae450eb63e4.png)
![ba3238a9](https://user-images.githubusercontent.com/904055/40884394-e1b65608-66e0-11e8-962d-b8ca4e657a96.png)

**Comment by moshee** [comment]
Ok, finally got around to merging your branch. Bypassed the normal PR thing to add my own stuff on top before committing to master.

Out of curiosity, I'm interested to know where you found out about this project. I have not done any promotion whatsoever so I am always surprised to find people starring and installing (this project was originally started on a bet...).

Thanks!

**Comment by ZackBoe** [comment]
Excited to upgrade my install, thanks!

It's been quite awhile since I started using Airlift, but I *think* I had just come across it searching Github as a whole for file host projects. I really like Airlift because pretty no nonsense and I can have super short URLs. Being just a single binary is pretty appealing too. Thanks for your work on it!
