### ISSUE TITLE
Install documentation

### ISSUE THREAD

**Issue by mayel** [moshee/airlift#34]
I ran into an issue when trying to install using `go get` because the docs include the -d flag which prevents it from installing.

**Comment by moshee** [comment]
I probably wasn't careful last time I edited the readme. Have you tried just not using -d?

**Comment by mayel** [comment]
Yeah that worked :) Notified you for the next person.

**Comment by moshee** [comment]
Ok, thanks. I'll leave this open until I get around to it.
