### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by camjac251** [moshee/airlift#38]
Hey there

Is development on this app on hold? I tested it with a 5GB file and after it was done uploaded, the link was made instantly which it amazing. I tested a few other scripts in node/php/go/python and some took a while to process after it was done uploading.

Do you know if the download speeds are being throttled? I tried downloading the file after uploading and it was stuck at 1MB/s

**Comment by moshee** [comment]
I've been busy with work and lazy with life so haven't really had a chance to work on this lately. It is not abandoned, just not broken enough to fix urgently.

Download speed sounds more like an implementation issue. Do you have it behind a reverse proxy or firewall? If it's directly listening on an open port, the speed should be limited by your connection.

**Comment by camjac251** [comment]
I tried it directly over the go web server, no proxies. It might've been a network issue at the time, I'll be sure to try it again.

I've been searching for a puush like clone but all of the featured ones are in PHP. This one beats them all in speed and efficiency. Is it possible to create multiple users? Is it locked to one at the moment?

**Comment by moshee** [comment]
Yep, single user only for simplicity. You could probably run multiple instances in different user accounts on your machine and assign them different ports with a reverse proxy if you wanted multi user.
