### ISSUE TITLE
Package static content like HTML and CSS with the binary.

### ISSUE THREAD

**Issue by franzf** [moshee/airlift#4]
The ideal solution would be having the binary extract files on launch to the process owner's $HOME/.airlift-server. Include some sort of versioning (hash checks?) so the binary knows when to overwrite content, but allow the user to edit his own copies by giving higher priority to local versions. (Ex: load .airlift-server/static/style-local.css over style.css?)

**Comment by drx** [comment]
> Include some sort of versioning (hash checks?) so the binary knows when to overwrite content, but allow the user to edit his own copies by giving higher priority to local versions. (Ex: load .airlift-server/static/style-local.css over style.css?)

Or simply check whether ~/.airlift-server exists to determine if airlift is being run for the first time.

**Comment by moshee** [comment]
There are two directories that need to be packaged with the binary: `templates/` and `static/`. I am considering having multiple locations to look for assets with a specific order of priorities:

1. Directories in `$PWD` (for development)
2. Directories in `~/.airlift-server/resources`
3. Assets packaged within the binary using a system similar to [rakyll/statik][1]

Binary packaged files should be part of a pluggable filesystem backend behind a basic interface to support the above locations.

One question I have is if there's a point for (2.), as that would mean having the files in two places to no real benefit. I prefer the binary packaged approach as this makes things super easy to install, not having to worry about paths or duplication.

Alternate solution: add a flag to point to the containing directory, defaulting to empty (= use binary packaged files) and set to `.` for development.

[1]: https://github.com/rakyll/statik

**Comment by franzf** [comment]
LGTM! :+1:
