### ISSUE TITLE
Updater mechanism

### ISSUE THREAD

**Issue by franzf** [moshee/airlift#5]
Include an updater mechanism (separate shell script?) that does the following:
* Checking against a known newest version (github releases?)
* Downloading and replacing the binary.
* Gracefully stopping the server and accepting requests on a new process.

A built in updater on the binary would be less than ideal, since we would want to leave airlift easily packageable by downstream, which already have their own package managers, et al.

**Comment by drx** [comment]
Instead of an update mechanism just include an install script. This updating would mean installing the new version over the old one.

**Comment by moshee** [comment]
I think packaging resources with the binary obviates the need for an install script. Everything needed to run is either generated by the binary or embedded in it. There are not that many significant files in various places, and the config file is just JSON (so backwards- and forwards-compatible)..

Thoughts?

**Comment by moshee** [comment]
Using Github releases now.

Also, if you install from source using `go get`, it should be as simple as `go get -u` to update. Binary runs from anywhere in `$PATH` now.
